name: Build and Push Docker Image

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Log in to GHCR using GitHub Actions token
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build and push image
            - name: Build and Push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/theantlers-backend:latest
                      ghcr.io/${{ github.repository_owner }}/theantlers-backend:${{ github.sha }}
